# Generated by Django 5.2.5 on 2025-08-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
